/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Material-style tokens (names match catalog HTML)
        tertiary: '#532800',
        'tertiary-container': '#743b00',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#a0c9ff',
        'on-tertiary-fixed': '#2f1400',
        'on-secondary-fixed-variant': '#304a55',
        'on-primary': '#ffffff',
        'on-primary-container': '#8ebdf9',
        'primary-container': '#0f4c81',
        'surface-tint': '#2d6197',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-variant': '#e0e3e5',
        'primary-fixed': '#d2e4ff',
        'on-primary-fixed': '#001c37',
        'error-container': '#ffdad6',
        'inverse-surface': '#2d3133',
        'surface-dim': '#d8dadc',
        'tertiary-fixed-dim': '#ffb780',
        surface: '#f7f9fb',
        'on-primary-fixed-variant': '#07497d',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'outline-variant': '#c2c7d1',
        'on-tertiary-container': '#f9a767',
        secondary: '#48626e',
        'secondary-fixed-dim': '#afcbd8',
        'inverse-primary': '#a0c9ff',
        'secondary-container': '#cbe7f5',
        'secondary-fixed': '#cbe7f5',
        'on-surface': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        outline: '#727780',
        'tertiary-fixed': '#ffdcc4',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'on-tertiary-fixed-variant': '#6f3800',
        'on-secondary-fixed': '#021f29',
        'on-secondary-container': '#4e6874',
        'on-surface-variant': '#42474f',
        background: '#f7f9fb',
        primary: '#00355f',
        error: '#ba1a1a',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        // Legacy scale kept for badges / one-off uses
        accent: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Public Sans', 'system-ui', 'sans-serif'],
        body: ['Public Sans', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Public Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        stitch: '0 32px 64px rgba(25, 28, 30, 0.06)',
        'stitch-dark': '0 32px 64px rgba(0, 0, 0, 0.35)',
      },
    },
  },
  plugins: [],
};
